# python urdf2usd.py --input data_rlbench/urdf/hockey/hockey_goal_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/hockey/hockey_stick.urdf
# python urdf2usd.py --input data_rlbench/urdf/hockey/hockey_ball.obj
# python urdf2usd.py --input data_rlbench/urdf/beat_the_buzz/wand.urdf
# python urdf2usd.py --input data_rlbench/urdf/beat_the_buzz/Cuboid.urdf
# python urdf2usd.py --input data_rlbench/urdf/block_pyramid/block_pyramid_plane.obj
# python urdf2usd.py --input data_rlbench/urdf/change_channel/tv_remote.urdf
# python urdf2usd.py --input data_rlbench/urdf/change_channel/tv_frame.obj
# python urdf2usd.py --input data_rlbench/urdf/change_clock/clock.urdf
# python urdf2usd.py --input data_rlbench/urdf/close_door/door_frame.urdf
# python urdf2usd.py --input data_rlbench/urdf/close_drawer/drawer_frame.urdf
# python urdf2usd.py --input data_rlbench/urdf/close_fridge/fridge_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/close_grill/grill.urdf
# python urdf2usd.py --input data_rlbench/urdf/close_jar/jar0.obj
# python urdf2usd.py --input data_rlbench/urdf/close_jar/jar1.obj
# python urdf2usd.py --input data_rlbench/urdf/close_jar/jar_lid0.obj
# python urdf2usd.py --input data_rlbench/urdf/close_laptop_lid/base.urdf
# python urdf2usd.py --input data_rlbench/urdf/close_laptop_lid/laptop_holder.urdf
# python urdf2usd.py --input data_rlbench/urdf/close_microwave/microwave_frame_resp.urdf
# python urdf2usd.py --input data_rlbench/urdf/hang_frame_on_hanger/frame.urdf
# python urdf2usd.py --input data_rlbench/urdf/hang_frame_on_hanger/task_wall.obj
# python urdf2usd.py --input data_rlbench/urdf/hang_frame_on_hanger/hanger.obj
# python urdf2usd.py --input data_rlbench/urdf/hit_ball_with_queue/queue.urdf
# python urdf2usd.py --input data_rlbench/urdf/insert_onto_square_peg/square_ring.urdf
# python urdf2usd.py --input data_rlbench/urdf/lamp_off/lamp_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/lamp_off/push_button_target.urdf
# python urdf2usd.py --input data_rlbench/urdf/lift_numbered_block/block1.urdf
# python urdf2usd.py --input data_rlbench/urdf/lift_numbered_block/block2.urdf
# python urdf2usd.py --input data_rlbench/urdf/lift_numbered_block/block3.urdf
# python urdf2usd.py --input data_rlbench/urdf/light_bulb_in/bulb0.obj
# python urdf2usd.py --input data_rlbench/urdf/light_bulb_in/bulb1.obj
# python urdf2usd.py --input data_rlbench/urdf/light_bulb_in/bulb_holder0.obj
# python urdf2usd.py --input data_rlbench/urdf/light_bulb_in/bulb_holder1.obj
# python urdf2usd.py --input data_rlbench/urdf/light_bulb_in/lamp_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/meat_off_grill/chicken_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/meat_off_grill/grill_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/meat_off_grill/steak_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/open_grill/grill.urdf
# python urdf2usd.py --input data_rlbench/urdf/open_jar/jar_lid0.obj
# python urdf2usd.py --input data_rlbench/urdf/open_jar/jar_lid1.obj
# python urdf2usd.py --input data_rlbench/urdf/open_jar/jar0.obj
# python urdf2usd.py --input data_rlbench/urdf/open_jar/jar1.obj
# python urdf2usd.py --input data_rlbench/urdf/open_jar/target.obj
# python urdf2usd.py --input data_rlbench/urdf/open_oven_try/oven_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/open_washing_machine/washer.urdf
# python urdf2usd.py --input data_rlbench/urdf/open_window_try/window_main.urdf
# python urdf2usd.py --input data_rlbench/urdf/open_wine_bottle/bottle.urdf
# python urdf2usd.py --input data_rlbench/urdf/phone_on_base/phone_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/phone_on_base/phone_case_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/pick_and_lift_small/triangular_prism.obj
# python urdf2usd.py --input data_rlbench/urdf/pick_and_lift_small/star_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/pick_and_lift_small/moon_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/pick_and_lift_small/cylinder.obj
# python urdf2usd.py --input data_rlbench/urdf/pick_up_cup/cup1_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/pick_up_cup/cup2_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/place_cups_try/mug_visual1.urdf
# python urdf2usd.py --input data_rlbench/urdf/place_cups_try/place_cups_holder_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/place_shape_in_shape_sorter/shape_sorter.urdf
# python urdf2usd.py --input data_rlbench/urdf/play_jenga/Cuboid.obj
# python urdf2usd.py --input data_rlbench/urdf/plug_charger_in_power_supply/charger.urdf
# python urdf2usd.py --input data_rlbench/urdf/plug_charger_in_power_supply/task_wall.obj
# python urdf2usd.py --input data_rlbench/urdf/plug_charger_in_power_supply/plug.urdf
# python urdf2usd.py --input data_rlbench/urdf/pour_from_cup_to_cup/cup_distractor_visual0.urdf
# python urdf2usd.py --input data_rlbench/urdf/pour_from_cup_to_cup/cup_distractor_visual1.urdf
# python urdf2usd.py --input data_rlbench/urdf/pour_from_cup_to_cup/cup_distractor_visual2.urdf
# python urdf2usd.py --input data_rlbench/urdf/pour_from_cup_to_cup/cup_target_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/pour_from_cup_to_cup/cup_source_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/press_switch_try/switch_main.urdf
# python urdf2usd.py --input data_rlbench/urdf/press_switch_try/task_wall.obj
# python urdf2usd.py --input data_rlbench/urdf/push_button/push_button_target.urdf
# python urdf2usd.py --input data_rlbench/urdf/push_buttons/push_buttons_target0.urdf
# python urdf2usd.py --input data_rlbench/urdf/push_buttons/push_buttons_target1.urdf
# python urdf2usd.py --input data_rlbench/urdf/push_buttons/push_buttons_target2.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/chocolate_jello_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/strawberry_jello_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/spam_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/sugar_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/crackers_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/mustard_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/soup_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_all_groceries_in_cupboard/cupboard.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_books_on_bookshelf/bookshelf_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_books_on_bookshelf/book0_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_books_on_bookshelf/book1_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_books_on_bookshelf/book2_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/chocolate_jello_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/strawberry_jello_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/soup_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/tuna_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/spam_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/sugar_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/coffee_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/mustard_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/cupboard.obj
# python urdf2usd.py --input data_rlbench/urdf/put_groceries_in_cupboard/crackers_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_item_in_drawer/drawer_frame.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_knife_in_knife_block/chopping_board_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_knife_in_knife_block/knife_block_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_knife_in_knife_block/knife_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_bottle_in_fridge_try/fridge_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_bottle_in_fridge_try/bottle_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_money_in_safe_try/dollar_stack.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_money_in_safe_try/safe_body.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_plate_in_colored_dish_rack_try/dish_rack.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_plate_in_colored_dish_rack_try/plate_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_plate_in_colored_dish_rack_try/plate_stand.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_rubbish_in_bin/bin_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_rubbish_in_bin/tomato1_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_rubbish_in_bin/tomato2_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_rubbish_in_bin/rubbish_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_shoes_in_box/box_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_shoes_in_box/shoe1_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_shoes_in_box/shoe2_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_toilet_roll_on_stand/toilet_roll_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_toilet_roll_on_stand/stand_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_tray_in_oven/tray_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/put_umbrella_in_umbrella_stand/umbrella_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/put_umbrella_in_umbrella_stand/stand_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/reach_and_drag/target0.urdf
# python urdf2usd.py --input data_rlbench/urdf/scoop_with_spatula/spatula_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/screw_nail/screw_driver.urdf
# python urdf2usd.py --input data_rlbench/urdf/screw_nail/block.urdf
# python urdf2usd.py --input data_rlbench/urdf/set_the_table/spoon_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/set_the_table/fork_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/set_the_table/knife_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/set_the_table/glass_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/set_the_table/plate_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/set_the_table/holder.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/white_kingside_rook.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/white_kingside_knight.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/white_kingside_bishop.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/white_queen.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/white_king.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/white_pawn_a.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/black_kingside_rook.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/black_kingside_knight.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/black_kingside_bishop.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/black_queen.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/black_king.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/black_pawn_a.urdf
# python urdf2usd.py --input data_rlbench/urdf/setup_chess/chess_board_base_visual.obj
# python urdf2usd.py --input data_rlbench/urdf/slide_block_to_target/target.urdf
# python urdf2usd.py --input data_rlbench/urdf/slide_cabinet_open_and_place_cups/cup_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/slide_cabinet_open_and_place_cups/cabinet_base.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_blocks/stack_blocks_target_plane.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_chairs/chair1.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_chairs/chair2.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_chairs/chair3.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_cups/cup1_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_cups/cup2_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_cups/cup3_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_wine/wine_bottle_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_wine/rack_bottom_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/stack_wine/rack_top_visual.urdf
# python urdf2usd.py --input data_rlbench/urdf/sweep_to_dustpan/Dustpan_4.urdf
# python urdf2usd.py --input data_rlbench/urdf/sweep_to_dustpan/sweep_to_dustpan_broom_visual.urdf
